// Auto-generated by build.js @ 2025-04-17T02:42:42.309Z
const workConfig = {
  id: "work121",
  title: "네에!? 마리 쨩으로 불경한 망상을 하는 선생님이 계시다구요!?",
  author: "kanroame",
  images: [] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};