// Auto-generated by build.js
const worksData = [
  {
    "id": "work01",
    "title": "paofan pixiv",
    "author": "paofan",
    "firstImage": "01.webp"
  },
  {
    "id": "work02",
    "title": "토라도라! 야한책",
    "author": "wagashi",
    "firstImage": "01.png"
  },
  {
    "id": "work03",
    "title": "토라도라!의 에로책 2",
    "author": "wagashi",
    "firstImage": "01.png"
  }
];