// Auto-generated by build.js @ 2025-04-10T04:08:21.668Z
// Contains a list of all works found in the 'works' directory. Sorted by ID descending (latest first).
const worksData = [
  {
    "id": "work11",
    "title": "비에 젖으면",
    "author": "Shika Yuno",
    "firstImage": "01.webp",
    "imageCount": 19
  },
  {
    "id": "work10",
    "title": "아미야+그외",
    "author": "Rainy Ghost",
    "firstImage": "01.png",
    "imageCount": 14
  },
  {
    "id": "work09",
    "title": "오노즈카 선배는 나쁜 사람",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 39
  },
  {
    "id": "work08",
    "title": "토라도라!의 에로책 3",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 16
  },
  {
    "id": "work07",
    "title": "하급 마술사, 음문에 물들다",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 57
  },
  {
    "id": "work06",
    "title": "메스가키 서큐버스들에게 착정당하는 책",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 33
  },
  {
    "id": "work05",
    "title": "M200",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 29
  },
  {
    "id": "work04",
    "title": "너는 항상 지기 싫어하는 사람",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 26
  },
  {
    "id": "work03",
    "title": "토라도라!의 에로책 2",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 25
  },
  {
    "id": "work02",
    "title": "토라도라! 야한책",
    "author": "wagashi",
    "firstImage": "01.png",
    "imageCount": 26
  },
  {
    "id": "work01",
    "title": "paofan pixiv",
    "author": "paofan",
    "firstImage": "01.png",
    "imageCount": 95
  }
]; // 가독성을 위해 null, 2 사용