// Auto-generated by build.js @ 2025-04-20T01:43:18.600Z
const workConfig = {
  id: "work166",
  title: "아이돌이랑 같이 노는 것뿐인 쉬운 일이에요.",
  author: "healthyman",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp",
  "15.webp",
  "16.webp",
  "17.webp",
  "18.webp",
  "19.webp",
  "20.webp",
  "21.webp",
  "22.webp",
  "23.webp",
  "24.webp",
  "25.webp",
  "26.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};