// Auto-generated by build.js @ 2025-04-10T11:13:41.251Z
const workConfig = {
  id: "work26",
  title: "abrasion",
  author: "Shika Yuno",
  images: [
  "000.webp",
  "001.webp",
  "002.webp",
  "003.webp",
  "004.webp",
  "005.webp",
  "006.webp",
  "007.webp",
  "008.webp",
  "009.webp",
  "010.webp",
  "011.webp",
  "012.webp",
  "013.webp",
  "014.webp",
  "015.webp",
  "016.webp",
  "017.webp",
  "018.webp",
  "999.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};