// Auto-generated by build.js @ 2025-04-10T02:41:43.560Z
const workConfig = {
  id: "work01",
  title: "paofan pixiv",
  author: "paofan",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};