// Auto-generated by build.js @ 2025-04-19T04:27:55.174Z
const workConfig = {
  id: "work87",
  title: "악마면서 착한 아가씨",
  author: "kirii nao",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp",
  "15.webp",
  "16.webp",
  "17.webp",
  "18.webp",
  "19.webp",
  "20.webp",
  "21.webp",
  "22.webp",
  "23.webp",
  "24.webp",
  "25.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};