// Auto-generated by build.js @ 2025-04-10T04:49:15.179Z
const workConfig = {
  id: "work14",
  title: "원교해도 정말 괜찮을 거야! ... 아마?",
  author: "Shika Yuno",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp",
  "15.webp",
  "16.webp",
  "17.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};