// Auto-generated by build.js @ 2025-04-17T03:39:33.568Z
const workConfig = {
  id: "work83",
  title: "어느 국어 교사의 망상록",
  author: "tamano kedama",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp",
  "15.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};