// Auto-generated by build.js @ 2025-04-10T06:51:42.399Z
const workConfig = {
  id: "work10",
  title: "아미야+그외",
  author: "Rainy Ghost",
  images: [
  "01.png",
  "02.png",
  "03.png",
  "04.png",
  "05.png",
  "06.png",
  "07.png",
  "08.png",
  "09.png",
  "10.png",
  "11.png",
  "12.png",
  "13.png",
  "14.png"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};