// Auto-generated by build.js @ 2025-04-10T03:20:42.209Z
const workConfig = {
  id: "work10",
  title: "오노즈카 선배는 나쁜 사람",
  author: "wagashi",
  images: [
  "01.png",
  "02.png",
  "03.png",
  "04.png",
  "05.png"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};