// Auto-generated by build.js @ 2025-04-20T01:43:18.783Z
const workConfig = {
  id: "work226",
  title: "들이닥친 마왕과 바다로 가다 후일담",
  author: "mikemono yuu",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};