// Auto-generated by build.js @ 2025-04-17T06:11:37.330Z
const workConfig = {
  id: "work138",
  title: "Hikaeme Request 2",
  author: "takota konu",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};