// Auto-generated by build.js @ 2025-04-20T01:25:16.322Z
const workConfig = {
  id: "work221",
  title: "컴페인 2",
  author: "kakei kei",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};