// Auto-generated by build.js @ 2025-04-17T06:19:07.626Z
const workConfig = {
  id: "work48",
  title: "여름에 돌아가는 건 조카(너)를 위해",
  author: "akadashi",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp",
  "15.webp",
  "16.webp",
  "17.webp",
  "18.webp",
  "19.webp",
  "20.webp",
  "21.webp",
  "22.webp",
  "23.webp",
  "24.webp",
  "25.webp",
  "26.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};