// Auto-generated by build.js @ 2025-04-20T01:06:42.751Z
const workConfig = {
  id: "work185",
  title: "JC 의 오마케",
  author: "kuromotokun",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};