// Auto-generated by build.js @ 2025-04-10T11:13:41.184Z
const workConfig = {
  id: "work04",
  title: "너는 항상 지기 싫어하는 사람",
  author: "wagashi",
  images: [
  "01.png",
  "02.png",
  "03.png",
  "04.png",
  "05.png",
  "06.png",
  "07.png",
  "08.png",
  "09.png",
  "10.png",
  "11.png",
  "12.png",
  "13.png",
  "14.png",
  "15.png",
  "16.png",
  "17.png",
  "18.png",
  "19.png",
  "20.png",
  "21.png",
  "22.png",
  "23.png",
  "24.png",
  "25.png",
  "26.png"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};