// Auto-generated by build.js @ 2025-04-17T03:39:33.369Z
const workConfig = {
  id: "work100",
  title: "되고 싶지 않았는데 서큐버스가 되어버린 야마다양 ~호텔로 데려가지는 편~",
  author: "kanroame",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp",
  "13.webp",
  "14.webp",
  "15.webp",
  "16.webp",
  "17.webp",
  "18.webp",
  "19.webp",
  "20.webp",
  "21.webp",
  "22.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};