// Auto-generated by build.js @ 2025-04-10T04:12:36.631Z
const workConfig = {
  id: "work08",
  title: "토라도라!의 에로책 3",
  author: "wagashi",
  images: [
  "01.png",
  "02.png",
  "03.png",
  "04.png",
  "05.png",
  "06.png",
  "07.png",
  "08.png",
  "09.png",
  "10.png",
  "11.png",
  "12.png",
  "13.png",
  "14.png",
  "15.png",
  "16.png"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};