// Auto-generated by build.js @ 2025-04-20T01:06:42.729Z
const workConfig = {
  id: "work179",
  title: "여친최면 Bunny",
  author: "santa",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp",
  "11.webp",
  "12.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};