// Auto-generated by build.js @ 2025-04-17T04:36:06.259Z
const workConfig = {
  id: "work86",
  title: "불법 컨셉카페에 주의♡",
  author: "tamano kedama",
  images: [
  "01.webp",
  "02.webp",
  "03.webp",
  "04.webp",
  "05.webp",
  "06.webp",
  "07.webp",
  "08.webp",
  "09.webp",
  "10.webp"
] // 감지된 이미지 목록 배열 (가독성을 위해 줄바꿈)
};